//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tasks()
        {
            this.Timesheets = new HashSet<Timesheets>();
        }
    
        public int TaskId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCreate { get; set; }
        public Nullable<System.DateTime> DeadlineDeta { get; set; }
        public Nullable<System.DateTime> DateFinished { get; set; }
        public Nullable<int> UserId { get; set; }
        public int CreaterId { get; set; }
        public int TaskStatus { get; set; }
        public int ProjectId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual UserProfiles UserProfiles { get; set; }
        public virtual UserProfiles UserProfiles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timesheets> Timesheets { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
