//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackerLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAuthData
    {
        public int UserId { get; set; }
        public string PasswordHash { get; set; }
        public string Apikey { get; set; }
    
        public virtual UserProfiles UserProfiles { get; set; }
    }
}
